linters:
  enable:
    - dogsled
    - dupl
    - gofmt
    - goimports
    - gosec
    - misspell
    - nakedret
    - stylecheck
    - unconvert
    - unparam
    - whitespace
linters-settings:
  stylecheck:
    go: "1.16"
    checks:
      - all
      - '-ST1003' # disable uppercase acronyms, like Google Go SDK
issues:
  exclude-rules:
    - path: openapi2/copy.go
      text: "`copyOrIgnoreEndpoint` - `path` is unused"
    - path: openapi2/copy.go
      text: "`copyOrIgnoreEndpoint` - `specOld` is unused"
