version: "2"
linters:
  enable:
    - dogsled
    - dupl
    - gosec
    - misspell
    - nakedret
    - staticcheck
    - unconvert
    - unparam
    - whitespace
  settings:
    staticcheck:
      checks:
        - -ST1003
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: openapi2/copy.go
        text: '`copyOrIgnoreEndpoint` - `path` is unused'
      - path: openapi2/copy.go
        text: '`copyOrIgnoreEndpoint` - `specOld` is unused'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
